In [1]:
from __future__ import print_function
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D, Conv2D
from keras.optimizers import SGD, Adam
from keras.utils import np_utils
import numpy as np
import pandas as pd

Using TensorFlow backend.


In [2]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [3]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float16') / 255
print(train_images.shape)

(60000, 28, 28, 1)


In [4]:
test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float16') / 255
print(test_images.shape)

(10000, 28, 28, 1)


In [5]:
print(train_labels[:5])
train_labels = to_categorical(train_labels)

test_labels = to_categorical(test_labels)
print(train_labels[:5, ])

[5 0 4 1 9]
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [6]:
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten_1 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                36928     
__________

In [7]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
import keras

callbacks = [
    keras.callbacks.TensorBoard(
        # Log files will be written at this location
        log_dir='work',
        #histogram_freq=1,
        # We will record activation histograms every 1 epoch

    )
]
history = model.fit(train_images, train_labels,
                    epochs=3,
                    batch_size=128,
                    validation_split=0.2,
                    callbacks=callbacks)

Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 [==============================] - 90s 2ms/step - loss: 0.3023 - acc: 0.9028 - val_loss: 0.0915 - val_acc: 0.9726
Epoch 2/3
48000/48000 [==============================] - 89s 2ms/step - loss: 0.0779 - acc: 0.9755 - val_loss: 0.0715 - val_acc: 0.9788
Epoch 3/3
48000/48000 [==============================] - 90s 2ms/step - loss: 0.0530 - acc: 0.9841 - val_loss: 0.0626 - val_acc: 0.9829
